//file:noinspection GroovyAssignabilityCheck
//file:noinspection GroovyAccessibility
//file:noinspection GradlePackageVersionRange
plugins {
	id "fabric-loom" version "1.10-SNAPSHOT"
	id "io.github.p03w.machete" version "1.+" // automatic jar compressing on build
	id "maven-publish"
}

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

// ArchivesBaseName is Used For The Name Of The Output Jar
archivesBaseName = "create-smorestuff-" + project.mod_version + project.archives_base_name
group = project.maven_group

version = "${mod_version}+${minecraft_version}"

repositories {
	maven { url = "https://maven.shedaniel.me/" } // Cloth Config
	maven { url = "https://maven.parchmentmc.org" } // Parchment mappings
	maven { url = "https://api.modrinth.com/maven" } // LazyDFU
	maven {url = "https://maven.terraformersmc.com/"} // Mod Menu, EMI
	maven { url = "https://mvn.devos.one/snapshots/" } // Create, Porting Lib, Forge Tags, Milk Lib, Registrate
	maven { url = "https://mvn.devos.one/releases/" } // Porting Lib Releases
	maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" } // Forge Config API Port
	maven { url = "https://maven.jamieswhiteshirt.com/libs-release" } // Reach Entity Attributes
	maven { url = "https://jitpack.io/" } // Mixin Extras, Fabric ASM
	maven { url = "https://maven.tterrag.com/" } // Flywheel

	maven {
		url = uri("https://maven.pkg.github.com/PlayerXess/Layered-Rendering-Engine")
		credentials {
			username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
			password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
		}
	}
}

configurations.configureEach {
	resolutionStrategy {
		force("net.fabricmc:fabric-loader:${fabric_loader_version}")
	}
}

dependencies {

	// Setup
	minecraft("com.mojang:minecraft:${minecraft_version}")

	mappings(loom.layered {
		it.mappings("net.fabricmc:yarn:${yarn_version}")
		it.parchment("org.parchmentmc.data:parchment-${minecraft_version}:${parchment_version}@zip")
	})
	modImplementation("net.fabricmc:fabric-loader:${fabric_loader_version}")

		// dependencies
	modImplementation("net.fabricmc.fabric-api:fabric-api:${fabric_api_version}")

	modImplementation("net.playerxess.plre:plre:${plre_version}")

	// Create - dependencies are added transitively
	modImplementation("com.simibubi.create:create-fabric-${minecraft_version}:${create_version}")

		// Development QOL

	// LazyDFU
	modLocalRuntime("maven.modrinth:lazydfu:${lazydfu_version}")

	// Mod Menu
	modLocalRuntime("com.terraformersmc:modmenu:${modmenu_version}")

	// EMI
	modCompileOnly "dev.emi:emi-fabric:${emi_version}+${minecraft_version}:api"
	modLocalRuntime "dev.emi:emi-fabric:${emi_version}+${minecraft_version}"
}

processResources {

	// require dependencies to be the version compiled against or newer
	Map<String, String> properties = Map.of(
			"version", version,
			"fabric_loader_version", fabric_loader_version,
			"fabric_api_version", fabric_api_version,
			"create_version", create_version,
			"minecraft_version", minecraft_version
	)

	inputs.properties(properties)

	filesMatching("fabric.mod.json") {
		expand properties
	}
}

fabricApi {
    configureDataGeneration()
}

machete {
	enabled = true
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = Integer.parseInt(sourceCompatibility)
}

java {
	withSourcesJar()
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archivesBaseName}" }
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
