# Gradle Settings
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod properties
mod = 0.1.0
maven_group = net.playerxess.smorestuff
archives_name = smorestuff
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft = 1.21.1
yarn_mappings = 1.21.1+build.1

# Global Dependencies
architectury_api = 13.0.8

# Fabric Dependencies
fabric_loader = 0.18.1
fabric_api = 0.116.7+1.21.1

# NeoForge Dependencies
neoforge = 21.1.215
yarn_mappings_patch_neoforge = 1.21+build.6

# Mod Dependencies

# Create NeoForge
create_neoforge=0 # TODO: Add Later

# Create Fabric
create_fabric=0 # TODO: Create Fabric Not Updated To 1.21.1 Yet

# Other